<a href="https://colab.research.google.com/github/Diptyregar456/Python/blob/main/numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**IMPORT THE NUMPY PACKAGE UNDER THE NAME NP**

In [ ]:
import numpy as np

**PRINT THE NUMPY VERSION AND THE CONFIGURATION**

In [ ]:
print(np.__version__)
np.show_config()

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


**CREATE A NULL FECTOR OD SIZE 10**

In [ ]:
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**HOW TO GET DOCUMENTATION OF NUMPY ADD FUNCTION FROM THE COMMAND LINE**

In [ ]:
#python-c import {"numpy; numpy.info(numpy.add)"}

**CREATE A NULL VECTOR OF SIZE 10 BUT THE FIFTH VALUE WHICH IS 1**

In [ ]:
z = np.zeros(10)
z[4] = 1
z[6] = 2
z

array([0., 0., 0., 0., 1., 0., 2., 0., 0., 0.])

**CREATE A VECTOR WITH VALUES RANGING FROM 10 TO 49**

In [ ]:
z = np.arange(10,49)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

**REVERSE A VECTOR(FIRST ELEMENT BECOMES LAST)**

In [ ]:
Z = np.arange(50)
Z = Z[::-1]
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

**CREATE A 3*3 MATRIX WITH THE VALUES RANGING FROM 0 TO 8**

In [ ]:
z = np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

FIND INDICES OF NON-ZERO ELEMENTS FROM [1,2,0,0,4,0]

In [ ]:
z = np.nonzero([1,2,0,0,4,0])
z
z = np.arange(1,9)
z

array([1, 2, 3, 4, 5, 6, 7, 8])

CREATE 3*3 IDENTITY matrix



In [ ]:
import numpy as np
z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**CREATE 3X3X3 ARRAY WITH RANDOM VALUES**

In [ ]:
z = np.random.random((3,3,3))
z

array([[[0.48526807, 0.3131007 , 0.90535717],
        [0.77781871, 0.12165774, 0.54699355],
        [0.12892484, 0.98336543, 0.41932789]],

       [[0.81471237, 0.00173151, 0.80640371],
        [0.48991584, 0.68340786, 0.49046123],
        [0.90110926, 0.30344956, 0.90103523]],

       [[0.77948959, 0.04946879, 0.25935624],
        [0.16671407, 0.2440538 , 0.515258  ],
        [0.15140111, 0.50416686, 0.38323058]]])

In [ ]:
z = np.random.randn(3,3)
z

array([[-0.96194712,  0.20682266,  0.15313474],
       [-1.68109021, -0.94071285, -0.34467517],
       [ 1.07603047, -0.83756113, -0.88815081]])

**CREATE A 10X10 ARRAY WITH RANDOM VALUES AAND FIND THE MINIMUM AND MAXIMUM VALUES**

In [ ]:
z = np.random.randn(10,10)
Zmin = z.min()
z
Zmax = z.max()
z
Zmean = z.mean()
z
Zstd = z.std()
z

array([[-0.56111877, -0.15550086, -0.50247054,  1.0706219 , -0.19776222,
         0.10425498,  0.73521978,  0.66347178,  0.43290139, -2.17165487],
       [ 0.14674205, -1.39213263, -0.12558176,  1.15958293,  0.79537737,
        -0.71059705,  0.47828422,  1.79525789,  0.97398621,  0.65332065],
       [-0.54791588,  1.48024753, -0.31630142,  0.03574591,  1.05053256,
         0.20657307,  0.23284223, -1.44566213,  0.45618435,  0.43770671],
       [ 1.31636197,  1.53157778,  1.2970364 , -0.17254205, -0.88606915,
        -1.91461669, -0.58126177, -1.2123435 , -1.12433119,  1.14182889],
       [-0.93474481,  0.88775474,  0.75702502,  1.50116564,  0.8476439 ,
        -0.11951077,  0.21541265, -0.4897184 , -0.14012315, -1.09173035],
       [-1.1503273 , -1.46676488, -0.44529266,  1.07592598, -0.71955391,
        -0.12848358,  0.89336201, -0.29992744, -0.06586135, -0.89453919],
       [ 0.20519823,  0.57887837, -1.53365603,  1.43900515, -1.72438683,
         0.50814094, -0.35357105, -0.17654876

**CREATE A RANDOM VECTOR OF SIZE 30 AND FIND THE MEAN VALUE**

In [ ]:
z = np.random.rand(30)
m = z.mean()
m

0.5277923736889063

**CREATE 2D ARRAY WITH 1 ON THE BORDER AND 0 INSIDE**

In [ ]:
import numpy as np
z = np.array((2,2))
z

array([2, 2])

In [ ]:
z = np.ones((10,10))
z[1:-1,1:-1] = 0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
z = np.eye(10,10)
z[1:-1,1:-1]=0
z   #so we use ones because we need 1 on the border and 0 inside the border

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

**WHAT IS THE RESULT OF THE FOLLOWING EXPRESSION**

In [ ]:
0*np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3*0.1

False

**CREATE A 5X5 MATRIX WITH VALUES 1,2,3,4 JUST BELOW THE DIAGONAL**

In [ ]:
z = np.diag(1+np.arange(5))
z

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

**CREATE 8X8 matrix and fill it with a checkerboard pattern**

In [ ]:
z = np.diag(1+np.arange(8))
z

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

In [ ]:
#fill it with checker board
z = np.zeros((8,8), dtype=int)
z[1::2,::2] = 1
z[::2,1::2] = 1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

**CONSIDER A (6,7,8) SHAPE ARRAY ,WHAT IS THE INDEX (X,Y,Z) OF THE 100 TH ELEMENT **

In [ ]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


**create cheacer board 8x8 matrix with tile function**

In [ ]:
z = np.tile(np.array([[0,1],[1,0]]),(4,4))
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

**5x5 random matrix**

In [ ]:
z = np.random.random((5,5))
z
z = np.random.random((5,5))
zmax,zmin = z.max(), z.min()
z = (z-zmin)/(zmax-zmin)
z

array([[0.1332465 , 0.        , 0.62068986, 0.17805565, 0.17926077],
       [0.39158522, 0.84066926, 0.84511752, 0.10974067, 0.64186861],
       [0.46577074, 0.15985734, 0.41411822, 0.42715008, 0.64448775],
       [0.90312914, 0.2777928 , 0.63326917, 0.90375298, 0.54335933],
       [1.        , 0.18045973, 0.35699979, 0.17489539, 0.81147412]])

CREATE A CUSTOM DTYPE THAT DESCRIBE A COLOR AS FOUR UNISGNED BYTES(RGBA)****

In [ ]:
color = np.dtype([('r',np.unyte,1)])

**MULTIPLY A 5X3 MATRIX BY 3X2**

In [ ]:
z = np.dot(np.ones((5,3)),np.ones((3,2)))
z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [ ]:
z = np.dot(np.arange(5,3),np.arange(3,2))
z

0

In [ ]:
z = np.dot(np.eye(5,3),np.eye(3,2))
z

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

**WHAT IS THE RESULT OF FOLLOWING EXPRESSION**

In [ ]:
np.array(0)//np.array(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [ ]:
np.array(0)//np.array(0.)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in floor_divide
  """Entry point for launching an IPython kernel.


nan

In [ ]:
np.array(0)/np.array(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [ ]:
np.array(0)/np.array(0.)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [ ]:
#nan = Convert a string or number to a floating point number, if possible.

In [ ]:
#5x5 matrix with row values ranging from 0 to 4
z = np.zeros((5,5))
z += np.arange(5)
z 

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [ ]:
z = np.random.random(10)
z.sort()
z

array([0.0481548 , 0.16280359, 0.17040703, 0.27236257, 0.43251089,
       0.48715091, 0.91959646, 0.95247475, 0.96915669, 0.9756076 ])

In [ ]:
#consider 2 random array A and b check if they are equal
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
equal

False

In [ ]:
#mZ[0] = 1